[config]
mode = 'dark'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.cache/matugen/colors.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '/home/AxisKnight/.config/rofi/colors.rasi'

[templates.hyprland]
input_path = '~/.config/matugen/templates/colors-hyprland.conf'
output_path = '~/.config/hypr/settings/colors-hyprland.conf'